import AppKit

// MARK: - 剪贴板内容模型

enum ClipboardContent: Equatable {
    case text(String)
    case image(Data)   // PNG data
    case files([URL])
}

struct ClipboardItem: Identifiable, Equatable {
    let id: UUID
    let date: Date
    let content: ClipboardContent

    init(id: UUID = UUID(), date: Date = Date(), content: ClipboardContent) {
        self.id = id
        self.date = date
        self.content = content
    }

    static func == (lhs: ClipboardItem, rhs: ClipboardItem) -> Bool {
        lhs.id == rhs.id
    }
}

// MARK: - 剪贴板读取

extension NSPasteboard.PasteboardType {
    /// 密码管理器等标记为「瞬时/敏感」的类型，不应进入历史记录
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

extension NSImage {
    func pngData() -> Data? {
        guard let tiff = tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}

enum ClipboardReader {
    /// 当前剪贴板里是否有「瞬时/敏感」标记（1Password 等）
    private static func isTransient(_ pb: NSPasteboard) -> Bool {
        guard let types = pb.types else { return false }
        return types.contains(.transient) || types.contains(.concealed) || types.contains(.autoGenerated)
    }

    /// 读取当前剪贴板内容（优先级：文件 > 图片 > 文本）
    static func currentContent() -> ClipboardContent? {
        let pb = NSPasteboard.general
        guard !isTransient(pb) else { return nil }

        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls)
        }
        if let png = currentImagePNG() {
            return .image(png)
        }
        if let str = pb.string(forType: .string), !str.isEmpty {
            return .text(str)
        }
        return nil
    }

    /// 只取剪贴板里的图片（用于 ⌥⌘V 保存）
    static func currentImagePNG() -> Data? {
        let pb = NSPasteboard.general
        guard !isTransient(pb) else { return nil }
        guard let images = pb.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
              let img = images.first else { return nil }
        return img.pngData()
    }
}

// MARK: - 历史记录存储（持久化到 ~/Library/Application Support/mactowin/history）

struct PersistedClipboardItem: Codable {
    let id: UUID
    let date: Date
    let kind: String          // text / image / files
    let text: String?
    let imageFile: String?
    let files: [String]?
}

final class ClipboardHistoryStore: ObservableObject {
    static let shared = ClipboardHistoryStore()

    @Published private(set) var items: [ClipboardItem] = []

    var limit: Int { SettingsStore.shared.historyLimit }

    private let storageDir: URL
    private var imagesDir: URL { storageDir.appendingPathComponent("images") }
    private var metadataURL: URL { storageDir.appendingPathComponent("history.json") }

    init(storageDir: URL? = nil) {
        self.storageDir = storageDir ?? FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("mactowin/history")
        load()
    }

    func add(_ content: ClipboardContent) {
        // 去重：相同内容移到最前
        items.removeAll { $0.content == content }
        items.insert(ClipboardItem(content: content), at: 0)
        if items.count > limit {
            items = Array(items.prefix(limit))
        }
        save()
    }

    func clear() {
        items.removeAll()
        try? FileManager.default.removeItem(at: imagesDir)
        save()
    }

    // MARK: 持久化

    private func save() {
        let fm = FileManager.default
        try? fm.createDirectory(at: imagesDir, withIntermediateDirectories: true)

        var persisted: [PersistedClipboardItem] = []
        for item in items {
            switch item.content {
            case .text(let s):
                persisted.append(PersistedClipboardItem(id: item.id, date: item.date, kind: "text", text: s, imageFile: nil, files: nil))
            case .image(let data):
                let name = item.id.uuidString + ".png"
                try? data.write(to: imagesDir.appendingPathComponent(name))
                persisted.append(PersistedClipboardItem(id: item.id, date: item.date, kind: "image", text: nil, imageFile: name, files: nil))
            case .files(let urls):
                persisted.append(PersistedClipboardItem(id: item.id, date: item.date, kind: "files", text: nil, imageFile: nil, files: urls.map { $0.path }))
            }
        }
        if let data = try? JSONEncoder().encode(persisted) {
            try? data.write(to: metadataURL, options: .atomic)
        }

        // 清理不再被引用的图片文件
        let referenced = Set(persisted.compactMap { $0.imageFile })
        if let onDisk = try? fm.contentsOfDirectory(atPath: imagesDir.path) {
            for file in onDisk where !referenced.contains(file) {
                try? fm.removeItem(at: imagesDir.appendingPathComponent(file))
            }
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: metadataURL),
              let persisted = try? JSONDecoder().decode([PersistedClipboardItem].self, from: data) else { return }
        items = persisted.compactMap { p in
            let content: ClipboardContent
            switch p.kind {
            case "text":
                guard let t = p.text else { return nil }
                content = .text(t)
            case "image":
                guard let f = p.imageFile,
                      let d = try? Data(contentsOf: imagesDir.appendingPathComponent(f)) else { return nil }
                content = .image(d)
            case "files":
                guard let fs = p.files else { return nil }
                content = .files(fs.map { URL(fileURLWithPath: $0) })
            default:
                return nil
            }
            return ClipboardItem(id: p.id, date: p.date, content: content)
        }
    }

    func copyToPasteboard(_ item: ClipboardItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.content {
        case .text(let s):
            pb.setString(s, forType: .string)
        case .image(let data):
            if let img = NSImage(data: data) {
                pb.writeObjects([img])
            }
        case .files(let urls):
            pb.writeObjects(urls as [NSPasteboardWriting])
        }
    }
}

// MARK: - 剪贴板监听

final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        let s = SettingsStore.shared
        guard s.appEnabled, s.historyEnabled else { return }
        guard let content = ClipboardReader.currentContent() else { return }
        ClipboardHistoryStore.shared.add(content)
    }
}
